Profile
colewarner24/CatalogRepoFE pull request #35
Opened 2022-05-20 21:52 UTC by FatRat60

Login and signup take you to Profile view where you can either edit profile, view pages, or view reviews. (Reviews not implemented yet) View pages takes you to a list of the pages associated with your account. You can then either click to add a new page or view one of the already created pages. When viewing a page you can opt to edit it.

2022-05-20 22:04 UTC, PanyaOu approved these changes
good add

2022-05-20 22:10 UTC, colewarner24 commented on src/TestLogin.js
> -import React, { useState } from 'react'
Delete testlogin and signup

2022-05-20 22:19 UTC, colewarner24 requested changes
merge updated main into code

2022-05-21 01:45 UTC, colewarner24 approved these changes
Code looks good go ahead and push

2022-05-22 00:10 UTC, closed without merging